{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "postman-token": "43c239ed-6756-65e3-ef36-ea252674eb24",
    "cache-control": "no-cache",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "content-type": "text/csv",
    "accept": "*/*",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employees",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employees",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/employees",
  "uriParams": {},
  "rawRequestUri": "/api/employees",
  "rawRequestPath": "/api/employees",
  "remoteAddress": "/127.0.0.1:55498",
  "requestPath": "/api/employees"
}